export type SignalSourceCategory = "Core" | "Recommended" | "Optional";
export type SignalSourceStatus = "connected" | "disconnected" | "locked";

export type SignalSource = {
  id: string;
  name: string;
  category: SignalSourceCategory;
  status: SignalSourceStatus;
  description: string;
  actionLabel: string;
  actionHref?: string;
  disabledReason?: string;
};

export const directoryIqSignalSources: SignalSource[] = [
  {
    id: "brilliant-directories",
    name: "Brilliant Directories API",
    category: "Core",
    status: "disconnected",
    description: "Listings and blog signal ingest surface for Brilliant Directories readiness.",
    actionLabel: "Configure",
    actionHref: "/directoryiq/signal-sources?connector=brilliant-directories",
  },
  {
    id: "openai",
    name: "OpenAI API (BYO)",
    category: "Core",
    status: "disconnected",
    description: "Entity normalization, signal synthesis, and authority blueprint drafting.",
    actionLabel: "Configure",
    actionHref: "/directoryiq/signal-sources?connector=openai",
  },
  {
    id: "serpapi",
    name: "SerpAPI",
    category: "Recommended",
    status: "disconnected",
    description: "Competitive set discovery and comparative clarity checks.",
    actionLabel: "Configure",
    actionHref: "/directoryiq/signal-sources?connector=serpapi",
  },
  {
    id: "ga4",
    name: "GA4",
    category: "Recommended",
    status: "disconnected",
    description: "Feedback loop for behavior signals and post-selection outcomes.",
    actionLabel: "Configure",
    actionHref: "/directoryiq/signal-sources?connector=ga4",
  },
  {
    id: "google-places",
    name: "Google Places / POI",
    category: "Optional",
    status: "locked",
    description: "Point-of-interest enrichment for directory coverage confidence.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "gbp",
    name: "Google Business Profile",
    category: "Optional",
    status: "locked",
    description: "Business profile consistency and trust context.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "geo-distance",
    name: "Maps / Geo Distance API",
    category: "Optional",
    status: "locked",
    description: "Proximity and regional relevance for local directory discovery.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "reviews-provider",
    name: "Reviews Provider",
    category: "Optional",
    status: "locked",
    description: "Reputation evidence stream for selection confidence.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "affiliate-feeds",
    name: "Affiliate / Booking Feeds",
    category: "Optional",
    status: "locked",
    description: "Commercial inventory sources for future ranking context.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
];

export const studioSignalSources: SignalSource[] = [
  {
    id: "youtube",
    name: "YouTube",
    category: "Core",
    status: "disconnected",
    description: "Channel and transcript ingest for narrative legibility.",
    actionLabel: "Configure",
    actionHref: "/studio/signal-sources?connector=youtube",
  },
  {
    id: "openai",
    name: "OpenAI API (BYO)",
    category: "Core",
    status: "disconnected",
    description: "Narrative synthesis, evidence mapping, and mention scaffolding.",
    actionLabel: "Configure",
    actionHref: "/studio/signal-sources?connector=openai",
  },
  {
    id: "podcast-rss",
    name: "Podcast RSS",
    category: "Recommended",
    status: "locked",
    description: "Episode ingestion for narrative continuity and reuse.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "file-ingestion",
    name: "File Ingestion (Drive/Dropbox/Upload)",
    category: "Recommended",
    status: "locked",
    description: "Bring source drafts and transcripts into the selection engine.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "web-docs",
    name: "Web Docs Ingestion",
    category: "Recommended",
    status: "locked",
    description: "Import supporting documentation as narrative evidence.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "alt-transcription",
    name: "Alt Transcription Provider",
    category: "Optional",
    status: "locked",
    description: "Optional Deepgram/AssemblyAI transcription redundancy.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "publishing-connectors",
    name: "Publishing Connectors",
    category: "Optional",
    status: "locked",
    description: "Distribution endpoints for multi-channel publishing.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "analytics",
    name: "Analytics",
    category: "Optional",
    status: "locked",
    description: "Narrative performance loop for iterative improvement.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
];

export const ecomviperSignalSources: SignalSource[] = [
  {
    id: "shopify",
    name: "Shopify OAuth",
    category: "Core",
    status: "locked",
    description: "Primary commerce catalog source for agent-facing product entities.",
    actionLabel: "Connect Shopify (OAuth) - coming next",
    disabledReason: "OAuth implementation is scheduled in a separate task.",
  },
  {
    id: "openai",
    name: "OpenAI API (BYO)",
    category: "Core",
    status: "disconnected",
    description: "Model credentials for selection reasoning and blueprint generation.",
    actionLabel: "Configure",
    actionHref: "/ecomviper/settings/integrations?connector=openai",
  },
  {
    id: "ga4",
    name: "GA4",
    category: "Recommended",
    status: "disconnected",
    description: "Behavior analytics for feedback-driven product selection.",
    actionLabel: "Configure",
    actionHref: "/ecomviper/settings/integrations?connector=ga4",
  },
  {
    id: "serpapi",
    name: "SerpAPI",
    category: "Recommended",
    status: "disconnected",
    description: "Visibility and competitor context for selection confidence.",
    actionLabel: "Configure",
    actionHref: "/ecomviper/settings/integrations?connector=serpapi",
  },
  {
    id: "reviews",
    name: "Reviews Platforms",
    category: "Optional",
    status: "locked",
    description: "Sentiment evidence for product trust weighting.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "support",
    name: "Support Signals",
    category: "Optional",
    status: "locked",
    description: "Support intent and friction signals for relevance calibration.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "shipping-returns",
    name: "Shipping / Returns",
    category: "Optional",
    status: "locked",
    description: "Operational trust indicators for selection quality.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
  {
    id: "merchant-center",
    name: "Merchant Center Feed",
    category: "Optional",
    status: "locked",
    description: "Future feed connector for external channel alignment.",
    actionLabel: "Coming Soon",
    disabledReason: "Connector scaffold only in this release.",
  },
];
