import { describe, expect, it } from "vitest";
import type { CasaHudCampaign } from "@/lib/studio/domara/campaigns";
import {
  deriveCasaHudWorkingListings,
  isCasaHudScriptPackageStale,
} from "@/lib/studio/domara/listing-working-set";

function baseCampaign(): CasaHudCampaign {
  return {
    id: "campaign-working-set",
    name: "Could You Retire in Southern Italy for Under $300K?",
    selectedViralTitle: "Could You Retire in Southern Italy for Under $300K?",
    selectedTitle: {
      title: "Could You Retire in Southern Italy for Under $300K?",
      score: 92,
      campaignType: "lifestyle_relocation",
      confidence: 0.89,
      reasoning: "Believable hook with strong intent.",
      regionHint: "Southern Italy",
      listingSearchHints: ["Southern Italy homes under 300k"],
    },
    titleCandidates: [],
    researchBrief: {
      summary: "Relocation opportunity.",
      opportunityCategories: [],
      competitorPatterns: [],
      audienceIntent: [],
      suggestedTitleDirections: [],
      riskNotes: [],
    },
    campaignType: "lifestyle_relocation",
    marketRegionHint: "Southern Italy",
    preferredMarket: "Italian real-estate YouTube",
    generationSource: {
      mode: "casahud_patterns",
      label: "CasaFlix opportunity patterns",
      detail: "Using strategy fallback.",
      canImproveWithYouTube: true,
    },
    confidenceReasoning: {
      summary: "Strong support.",
      titleOpportunitySummary: "Good fit.",
      selectedTitleReasoning: "Balanced.",
      selectedTitleConfidence: 0.89,
    },
    status: "listing_candidates_discovered",
    listingCandidates: [],
    listingSearchCriteria: null,
    listingProviderStatuses: [],
    discoverySummary: null,
    listingDiscoveryStatus: "listing_candidates_discovered",
    approvedListings: [],
    rejectedListings: [],
    listingRankOrder: [],
    listingValidationStatus: "not_started",
    listingValidationSummary: null,
    titleSupportConfidence: null,
    validationWarnings: [],
    locationIntelligenceStatus: "not_started",
    locationIntelligenceSummary: null,
    locationStory: null,
    localHighlights: [],
    poiBundle: null,
    mapSceneIdeas: [],
    listingLocationInsights: [],
    locationProviderStatuses: [],
    locationWarnings: [],
    scriptGenerationStatus: "not_started",
    scriptSummary: null,
    openingHook: null,
    estimatedDurationSeconds: null,
    tone: null,
    scriptSegments: [],
    propertySegments: [],
    locationLifestyleLines: [],
    transitions: [],
    closingCta: null,
    toneAndPacingNotes: [],
    scriptWarnings: [],
    scriptProviderStatus: null,
    fullScriptText: null,
    mediaPlanningStatus: "not_started",
    mediaPlanSummary: null,
    visualAssets: [],
    sceneAssetMapping: [],
    shotList: [],
    listingImageCoverage: [],
    mapLocationVisualPlan: [],
    thumbnailCandidateInputs: [],
    missingMediaWarnings: [],
    mediaProviderStatuses: [],
    youtubePackageStatus: "not_started",
    finalTitle: null,
    titleRationale: null,
    youtubeDescription: null,
    youtubeTags: [],
    youtubeHashtags: [],
    youtubeChapters: [],
    thumbnailConcept: null,
    publishMetadataDraft: null,
    packagingSummary: null,
    packageWarnings: [],
    packageProviderStatus: null,
    reviewStatus: "not_started",
    reviewSummary: null,
    reviewFindings: [],
    reviewBlockers: [],
    reviewWarnings: [],
    recommendedFixes: [],
    readinessScore: null,
    readinessExplanation: null,
    renderPlanStatus: "not_started",
    renderPlan: null,
    previewPackage: null,
    renderBlockers: [],
    approvalStatus: "pending",
    approvedAt: null,
    approvedBy: null,
    renderStatus: "not_started",
    renderJobId: null,
    renderOutput: null,
    renderOutputUrl: null,
    renderOutputPath: null,
    renderProviderStatus: null,
    renderWarnings: [],
    renderErrors: [],
    renderRunHistory: [],
    publishStatus: "not_ready",
    publishedVideoId: null,
    publishedVideoUrl: null,
    publishProviderStatus: null,
    publishWarnings: [],
    publishErrors: [],
    publishRunHistory: [],
    scheduleStatus: "not_scheduled",
    scheduledPublishAt: null,
    scheduleProviderStatus: null,
    scheduleWarnings: [],
    scheduleErrors: [],
    scheduleRunHistory: [],
    executionRunHistory: [],
    finalState: null,
    nextPhase: {
      key: "listing_validation",
      label: "Validate and rank listings",
      detail: "Validation and ranking arrive next.",
      implemented: false,
    },
    createdAt: "2026-05-02T00:00:00.000Z",
    updatedAt: "2026-05-02T00:00:00.000Z",
    generatedAt: "2026-05-02T00:00:00.000Z",
    futureState: {
      listingCandidates: [],
      approvedListings: [],
      rejectedListings: [],
      listingRankOrder: [],
      locationIntelligence: null,
      mapPoiBundle: null,
      script: null,
      storyboard: null,
      mediaPlan: null,
      packaging: null,
      renderStatus: null,
      reviewStatus: null,
      approvalStatus: null,
      publishStatus: null,
      scheduleStatus: null,
    },
  };
}

describe("CasaFlix listing working set", () => {
  it("promotes complete browser imports into the working shortlist", () => {
    const campaign = baseCampaign();
    campaign.listingCandidates = [
      {
        id: "listing-browser-ready",
        provider: "immobiliare",
        sourceType: "browser_assisted_import",
        sourceUrl: "https://www.immobiliare.it/en/annunci/127142643/",
        title: "Contrada Lacagnina Messina Single family villa with Terrace",
        locationText: "Acqualadrone - Sparta, Messina, Sicily, Italy",
        city: "Messina",
        region: "Sicily",
        country: "Italy",
        price: 300000,
        currency: "EUR",
        propertyType: "Single family villa",
        rooms: 5,
        bathrooms: 2,
        sizeSqm: 187,
        descriptionSnippet: "Seaside villa with complete listing facts.",
        features: ["5+ rooms", "2 bathrooms", "187 sqm"],
        imageUrls: ["https://images.example.com/messina-villa.jpg"],
        imageCount: 1,
        photoAvailability: "limited",
        featuredImageUrl: "https://images.example.com/messina-villa.jpg",
        manualCompletionStatus: "completed",
        discoveredAt: "2026-05-02T00:00:00.000Z",
        preliminaryMatchNotes: "Complete browser import.",
      },
    ];

    const working = deriveCasaHudWorkingListings(campaign);
    expect(working).toHaveLength(1);
    expect(working[0]?.id).toBe("listing-browser-ready");
    expect(working[0]?.validationStatus).toBe("approved");
  });

  it("ignores demo approved listings when real script-ready listings are present", () => {
    const campaign = baseCampaign();
    campaign.approvedListings = [
      {
        id: "demo-approved",
        provider: "casahud_sample",
        sourceType: "sample_pattern",
        title: "Demo Tropea listing",
        locationText: "Tropea, Calabria, Italy",
        city: "Tropea",
        region: "Calabria",
        country: "Italy",
        features: [],
        imageUrls: [],
        imageCount: 0,
        photoAvailability: "none",
        discoveredAt: "2026-05-02T00:00:00.000Z",
        preliminaryMatchNotes: "Demo listing",
        validationStatus: "approved",
        overallScore: 60,
        scoreBreakdown: {
          titleMatchScore: 60,
          geographyScore: 60,
          priceFitScore: 60,
          propertyTypeScore: 60,
          featureClaimScore: 60,
          mediaAvailabilityScore: 40,
          listingCompletenessScore: 40,
          providerQualityScore: 40,
          uniquenessScore: 80,
          overallScore: 60,
        },
        validationReasons: [],
        warnings: [],
      },
    ] as CasaHudCampaign["approvedListings"];
    campaign.listingCandidates = [
      {
        id: "listing-browser-ready",
        provider: "immobiliare",
        sourceType: "browser_assisted_import",
        sourceUrl: "https://www.immobiliare.it/en/annunci/127142643/",
        title: "Messina villa",
        locationText: "Messina, Sicily, Italy",
        city: "Messina",
        region: "Sicily",
        country: "Italy",
        price: 300000,
        currency: "EUR",
        propertyType: "Single family villa",
        rooms: 5,
        bathrooms: 2,
        sizeSqm: 187,
        descriptionSnippet: "Complete browser import.",
        features: ["5+ rooms", "187 sqm"],
        imageUrls: ["https://images.example.com/messina.jpg"],
        imageCount: 1,
        photoAvailability: "limited",
        featuredImageUrl: "https://images.example.com/messina.jpg",
        manualCompletionStatus: "completed",
        discoveredAt: "2026-05-02T00:00:00.000Z",
        preliminaryMatchNotes: "Complete browser import.",
      },
    ];

    const working = deriveCasaHudWorkingListings(campaign);
    expect(working).toHaveLength(1);
    expect(working[0]?.provider).toBe("immobiliare");
    expect(working[0]?.id).toBe("listing-browser-ready");
  });

  it("marks script packages stale against the working shortlist, not just approved listings", () => {
    const campaign = baseCampaign();
    campaign.scriptGenerationStatus = "script_generated";
    campaign.propertySegments = [
      {
        listingId: "old-listing",
        title: "Old listing",
        locationText: "Tropea, Calabria, Italy",
        narration: "Old script segment",
        whyItMadeTheCut: "Old",
        supportedFacts: [],
      },
    ];
    campaign.listingCandidates = [
      {
        id: "listing-browser-ready",
        provider: "immobiliare",
        sourceType: "browser_assisted_import",
        sourceUrl: "https://www.immobiliare.it/en/annunci/127142643/",
        title: "Messina villa",
        locationText: "Messina, Sicily, Italy",
        city: "Messina",
        region: "Sicily",
        country: "Italy",
        price: 300000,
        currency: "EUR",
        propertyType: "Single family villa",
        rooms: 5,
        bathrooms: 2,
        sizeSqm: 187,
        descriptionSnippet: "Complete browser import.",
        features: ["5+ rooms", "187 sqm"],
        imageUrls: ["https://images.example.com/messina.jpg"],
        imageCount: 1,
        photoAvailability: "limited",
        featuredImageUrl: "https://images.example.com/messina.jpg",
        manualCompletionStatus: "completed",
        discoveredAt: "2026-05-02T00:00:00.000Z",
        preliminaryMatchNotes: "Complete browser import.",
      },
    ];

    expect(isCasaHudScriptPackageStale(campaign)).toBe(true);
  });
});
